/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedYearOverviewRouteImport } from './routes/_authenticated/year-overview'
import { Route as AuthenticatedTimelineRouteImport } from './routes/_authenticated/timeline'
import { Route as AuthenticatedTasksRouteImport } from './routes/_authenticated/tasks'
import { Route as AuthenticatedPrincipalRouteImport } from './routes/_authenticated/principal'
import { Route as AuthenticatedGuideRouteImport } from './routes/_authenticated/guide'
import { Route as AuthenticatedEconomyRouteImport } from './routes/_authenticated/economy'
import { Route as AuthenticatedDocumentsRouteImport } from './routes/_authenticated/documents'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedContactsRouteImport } from './routes/_authenticated/contacts'
import { Route as AuthenticatedCasesRouteImport } from './routes/_authenticated/cases'
import { Route as AuthenticatedActivitiesRouteImport } from './routes/_authenticated/activities'
import { Route as AuthenticatedGuideIndexRouteImport } from './routes/_authenticated/guide.index'
import { Route as AuthenticatedGuideVidareutvecklingRouteImport } from './routes/_authenticated/guide.vidareutveckling'
import { Route as AuthenticatedGuideRedovisningsarRouteImport } from './routes/_authenticated/guide.redovisningsar'
import { Route as AuthenticatedGuideModulerRouteImport } from './routes/_authenticated/guide.moduler'
import { Route as AuthenticatedGuideKomIgangRouteImport } from './routes/_authenticated/guide.kom-igang'
import { Route as AuthenticatedGuideEkonomiRouteImport } from './routes/_authenticated/guide.ekonomi'
import { Route as AuthenticatedGuideArbetsflodeRouteImport } from './routes/_authenticated/guide.arbetsflode'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedYearOverviewRoute =
  AuthenticatedYearOverviewRouteImport.update({
    id: '/year-overview',
    path: '/year-overview',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedTimelineRoute = AuthenticatedTimelineRouteImport.update({
  id: '/timeline',
  path: '/timeline',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTasksRoute = AuthenticatedTasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPrincipalRoute = AuthenticatedPrincipalRouteImport.update({
  id: '/principal',
  path: '/principal',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedGuideRoute = AuthenticatedGuideRouteImport.update({
  id: '/guide',
  path: '/guide',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedEconomyRoute = AuthenticatedEconomyRouteImport.update({
  id: '/economy',
  path: '/economy',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDocumentsRoute = AuthenticatedDocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedContactsRoute = AuthenticatedContactsRouteImport.update({
  id: '/contacts',
  path: '/contacts',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCasesRoute = AuthenticatedCasesRouteImport.update({
  id: '/cases',
  path: '/cases',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedActivitiesRoute = AuthenticatedActivitiesRouteImport.update({
  id: '/activities',
  path: '/activities',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedGuideIndexRoute = AuthenticatedGuideIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedGuideRoute,
} as any)
const AuthenticatedGuideVidareutvecklingRoute =
  AuthenticatedGuideVidareutvecklingRouteImport.update({
    id: '/vidareutveckling',
    path: '/vidareutveckling',
    getParentRoute: () => AuthenticatedGuideRoute,
  } as any)
const AuthenticatedGuideRedovisningsarRoute =
  AuthenticatedGuideRedovisningsarRouteImport.update({
    id: '/redovisningsar',
    path: '/redovisningsar',
    getParentRoute: () => AuthenticatedGuideRoute,
  } as any)
const AuthenticatedGuideModulerRoute =
  AuthenticatedGuideModulerRouteImport.update({
    id: '/moduler',
    path: '/moduler',
    getParentRoute: () => AuthenticatedGuideRoute,
  } as any)
const AuthenticatedGuideKomIgangRoute =
  AuthenticatedGuideKomIgangRouteImport.update({
    id: '/kom-igang',
    path: '/kom-igang',
    getParentRoute: () => AuthenticatedGuideRoute,
  } as any)
const AuthenticatedGuideEkonomiRoute =
  AuthenticatedGuideEkonomiRouteImport.update({
    id: '/ekonomi',
    path: '/ekonomi',
    getParentRoute: () => AuthenticatedGuideRoute,
  } as any)
const AuthenticatedGuideArbetsflodeRoute =
  AuthenticatedGuideArbetsflodeRouteImport.update({
    id: '/arbetsflode',
    path: '/arbetsflode',
    getParentRoute: () => AuthenticatedGuideRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/activities': typeof AuthenticatedActivitiesRoute
  '/cases': typeof AuthenticatedCasesRoute
  '/contacts': typeof AuthenticatedContactsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/documents': typeof AuthenticatedDocumentsRoute
  '/economy': typeof AuthenticatedEconomyRoute
  '/guide': typeof AuthenticatedGuideRouteWithChildren
  '/principal': typeof AuthenticatedPrincipalRoute
  '/tasks': typeof AuthenticatedTasksRoute
  '/timeline': typeof AuthenticatedTimelineRoute
  '/year-overview': typeof AuthenticatedYearOverviewRoute
  '/guide/arbetsflode': typeof AuthenticatedGuideArbetsflodeRoute
  '/guide/ekonomi': typeof AuthenticatedGuideEkonomiRoute
  '/guide/kom-igang': typeof AuthenticatedGuideKomIgangRoute
  '/guide/moduler': typeof AuthenticatedGuideModulerRoute
  '/guide/redovisningsar': typeof AuthenticatedGuideRedovisningsarRoute
  '/guide/vidareutveckling': typeof AuthenticatedGuideVidareutvecklingRoute
  '/guide/': typeof AuthenticatedGuideIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/activities': typeof AuthenticatedActivitiesRoute
  '/cases': typeof AuthenticatedCasesRoute
  '/contacts': typeof AuthenticatedContactsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/documents': typeof AuthenticatedDocumentsRoute
  '/economy': typeof AuthenticatedEconomyRoute
  '/principal': typeof AuthenticatedPrincipalRoute
  '/tasks': typeof AuthenticatedTasksRoute
  '/timeline': typeof AuthenticatedTimelineRoute
  '/year-overview': typeof AuthenticatedYearOverviewRoute
  '/guide/arbetsflode': typeof AuthenticatedGuideArbetsflodeRoute
  '/guide/ekonomi': typeof AuthenticatedGuideEkonomiRoute
  '/guide/kom-igang': typeof AuthenticatedGuideKomIgangRoute
  '/guide/moduler': typeof AuthenticatedGuideModulerRoute
  '/guide/redovisningsar': typeof AuthenticatedGuideRedovisningsarRoute
  '/guide/vidareutveckling': typeof AuthenticatedGuideVidareutvecklingRoute
  '/guide': typeof AuthenticatedGuideIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/activities': typeof AuthenticatedActivitiesRoute
  '/_authenticated/cases': typeof AuthenticatedCasesRoute
  '/_authenticated/contacts': typeof AuthenticatedContactsRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/documents': typeof AuthenticatedDocumentsRoute
  '/_authenticated/economy': typeof AuthenticatedEconomyRoute
  '/_authenticated/guide': typeof AuthenticatedGuideRouteWithChildren
  '/_authenticated/principal': typeof AuthenticatedPrincipalRoute
  '/_authenticated/tasks': typeof AuthenticatedTasksRoute
  '/_authenticated/timeline': typeof AuthenticatedTimelineRoute
  '/_authenticated/year-overview': typeof AuthenticatedYearOverviewRoute
  '/_authenticated/guide/arbetsflode': typeof AuthenticatedGuideArbetsflodeRoute
  '/_authenticated/guide/ekonomi': typeof AuthenticatedGuideEkonomiRoute
  '/_authenticated/guide/kom-igang': typeof AuthenticatedGuideKomIgangRoute
  '/_authenticated/guide/moduler': typeof AuthenticatedGuideModulerRoute
  '/_authenticated/guide/redovisningsar': typeof AuthenticatedGuideRedovisningsarRoute
  '/_authenticated/guide/vidareutveckling': typeof AuthenticatedGuideVidareutvecklingRoute
  '/_authenticated/guide/': typeof AuthenticatedGuideIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/activities'
    | '/cases'
    | '/contacts'
    | '/dashboard'
    | '/documents'
    | '/economy'
    | '/guide'
    | '/principal'
    | '/tasks'
    | '/timeline'
    | '/year-overview'
    | '/guide/arbetsflode'
    | '/guide/ekonomi'
    | '/guide/kom-igang'
    | '/guide/moduler'
    | '/guide/redovisningsar'
    | '/guide/vidareutveckling'
    | '/guide/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/activities'
    | '/cases'
    | '/contacts'
    | '/dashboard'
    | '/documents'
    | '/economy'
    | '/principal'
    | '/tasks'
    | '/timeline'
    | '/year-overview'
    | '/guide/arbetsflode'
    | '/guide/ekonomi'
    | '/guide/kom-igang'
    | '/guide/moduler'
    | '/guide/redovisningsar'
    | '/guide/vidareutveckling'
    | '/guide'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/activities'
    | '/_authenticated/cases'
    | '/_authenticated/contacts'
    | '/_authenticated/dashboard'
    | '/_authenticated/documents'
    | '/_authenticated/economy'
    | '/_authenticated/guide'
    | '/_authenticated/principal'
    | '/_authenticated/tasks'
    | '/_authenticated/timeline'
    | '/_authenticated/year-overview'
    | '/_authenticated/guide/arbetsflode'
    | '/_authenticated/guide/ekonomi'
    | '/_authenticated/guide/kom-igang'
    | '/_authenticated/guide/moduler'
    | '/_authenticated/guide/redovisningsar'
    | '/_authenticated/guide/vidareutveckling'
    | '/_authenticated/guide/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/year-overview': {
      id: '/_authenticated/year-overview'
      path: '/year-overview'
      fullPath: '/year-overview'
      preLoaderRoute: typeof AuthenticatedYearOverviewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/timeline': {
      id: '/_authenticated/timeline'
      path: '/timeline'
      fullPath: '/timeline'
      preLoaderRoute: typeof AuthenticatedTimelineRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/tasks': {
      id: '/_authenticated/tasks'
      path: '/tasks'
      fullPath: '/tasks'
      preLoaderRoute: typeof AuthenticatedTasksRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/principal': {
      id: '/_authenticated/principal'
      path: '/principal'
      fullPath: '/principal'
      preLoaderRoute: typeof AuthenticatedPrincipalRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/guide': {
      id: '/_authenticated/guide'
      path: '/guide'
      fullPath: '/guide'
      preLoaderRoute: typeof AuthenticatedGuideRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/economy': {
      id: '/_authenticated/economy'
      path: '/economy'
      fullPath: '/economy'
      preLoaderRoute: typeof AuthenticatedEconomyRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/documents': {
      id: '/_authenticated/documents'
      path: '/documents'
      fullPath: '/documents'
      preLoaderRoute: typeof AuthenticatedDocumentsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/contacts': {
      id: '/_authenticated/contacts'
      path: '/contacts'
      fullPath: '/contacts'
      preLoaderRoute: typeof AuthenticatedContactsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/cases': {
      id: '/_authenticated/cases'
      path: '/cases'
      fullPath: '/cases'
      preLoaderRoute: typeof AuthenticatedCasesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/activities': {
      id: '/_authenticated/activities'
      path: '/activities'
      fullPath: '/activities'
      preLoaderRoute: typeof AuthenticatedActivitiesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/guide/': {
      id: '/_authenticated/guide/'
      path: '/'
      fullPath: '/guide/'
      preLoaderRoute: typeof AuthenticatedGuideIndexRouteImport
      parentRoute: typeof AuthenticatedGuideRoute
    }
    '/_authenticated/guide/vidareutveckling': {
      id: '/_authenticated/guide/vidareutveckling'
      path: '/vidareutveckling'
      fullPath: '/guide/vidareutveckling'
      preLoaderRoute: typeof AuthenticatedGuideVidareutvecklingRouteImport
      parentRoute: typeof AuthenticatedGuideRoute
    }
    '/_authenticated/guide/redovisningsar': {
      id: '/_authenticated/guide/redovisningsar'
      path: '/redovisningsar'
      fullPath: '/guide/redovisningsar'
      preLoaderRoute: typeof AuthenticatedGuideRedovisningsarRouteImport
      parentRoute: typeof AuthenticatedGuideRoute
    }
    '/_authenticated/guide/moduler': {
      id: '/_authenticated/guide/moduler'
      path: '/moduler'
      fullPath: '/guide/moduler'
      preLoaderRoute: typeof AuthenticatedGuideModulerRouteImport
      parentRoute: typeof AuthenticatedGuideRoute
    }
    '/_authenticated/guide/kom-igang': {
      id: '/_authenticated/guide/kom-igang'
      path: '/kom-igang'
      fullPath: '/guide/kom-igang'
      preLoaderRoute: typeof AuthenticatedGuideKomIgangRouteImport
      parentRoute: typeof AuthenticatedGuideRoute
    }
    '/_authenticated/guide/ekonomi': {
      id: '/_authenticated/guide/ekonomi'
      path: '/ekonomi'
      fullPath: '/guide/ekonomi'
      preLoaderRoute: typeof AuthenticatedGuideEkonomiRouteImport
      parentRoute: typeof AuthenticatedGuideRoute
    }
    '/_authenticated/guide/arbetsflode': {
      id: '/_authenticated/guide/arbetsflode'
      path: '/arbetsflode'
      fullPath: '/guide/arbetsflode'
      preLoaderRoute: typeof AuthenticatedGuideArbetsflodeRouteImport
      parentRoute: typeof AuthenticatedGuideRoute
    }
  }
}

interface AuthenticatedGuideRouteChildren {
  AuthenticatedGuideArbetsflodeRoute: typeof AuthenticatedGuideArbetsflodeRoute
  AuthenticatedGuideEkonomiRoute: typeof AuthenticatedGuideEkonomiRoute
  AuthenticatedGuideKomIgangRoute: typeof AuthenticatedGuideKomIgangRoute
  AuthenticatedGuideModulerRoute: typeof AuthenticatedGuideModulerRoute
  AuthenticatedGuideRedovisningsarRoute: typeof AuthenticatedGuideRedovisningsarRoute
  AuthenticatedGuideVidareutvecklingRoute: typeof AuthenticatedGuideVidareutvecklingRoute
  AuthenticatedGuideIndexRoute: typeof AuthenticatedGuideIndexRoute
}

const AuthenticatedGuideRouteChildren: AuthenticatedGuideRouteChildren = {
  AuthenticatedGuideArbetsflodeRoute: AuthenticatedGuideArbetsflodeRoute,
  AuthenticatedGuideEkonomiRoute: AuthenticatedGuideEkonomiRoute,
  AuthenticatedGuideKomIgangRoute: AuthenticatedGuideKomIgangRoute,
  AuthenticatedGuideModulerRoute: AuthenticatedGuideModulerRoute,
  AuthenticatedGuideRedovisningsarRoute: AuthenticatedGuideRedovisningsarRoute,
  AuthenticatedGuideVidareutvecklingRoute:
    AuthenticatedGuideVidareutvecklingRoute,
  AuthenticatedGuideIndexRoute: AuthenticatedGuideIndexRoute,
}

const AuthenticatedGuideRouteWithChildren =
  AuthenticatedGuideRoute._addFileChildren(AuthenticatedGuideRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedActivitiesRoute: typeof AuthenticatedActivitiesRoute
  AuthenticatedCasesRoute: typeof AuthenticatedCasesRoute
  AuthenticatedContactsRoute: typeof AuthenticatedContactsRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedDocumentsRoute: typeof AuthenticatedDocumentsRoute
  AuthenticatedEconomyRoute: typeof AuthenticatedEconomyRoute
  AuthenticatedGuideRoute: typeof AuthenticatedGuideRouteWithChildren
  AuthenticatedPrincipalRoute: typeof AuthenticatedPrincipalRoute
  AuthenticatedTasksRoute: typeof AuthenticatedTasksRoute
  AuthenticatedTimelineRoute: typeof AuthenticatedTimelineRoute
  AuthenticatedYearOverviewRoute: typeof AuthenticatedYearOverviewRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedActivitiesRoute: AuthenticatedActivitiesRoute,
  AuthenticatedCasesRoute: AuthenticatedCasesRoute,
  AuthenticatedContactsRoute: AuthenticatedContactsRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedDocumentsRoute: AuthenticatedDocumentsRoute,
  AuthenticatedEconomyRoute: AuthenticatedEconomyRoute,
  AuthenticatedGuideRoute: AuthenticatedGuideRouteWithChildren,
  AuthenticatedPrincipalRoute: AuthenticatedPrincipalRoute,
  AuthenticatedTasksRoute: AuthenticatedTasksRoute,
  AuthenticatedTimelineRoute: AuthenticatedTimelineRoute,
  AuthenticatedYearOverviewRoute: AuthenticatedYearOverviewRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
